import type { ThemeTypes } from "~/types/theme";

const DEFAULT_LIGHT_THEME: ThemeTypes = {
  name: "DEFAULT_LIGHT_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#4a8f7c",
    secondary: "#CCDA4E",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#F4F9FB",
    lightsecondary: "#FAFBEF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
    // vuetify purple
    purple: "#9C27B0",
    "purple-lighten-5": "#F3E5F5",
    "purple-lighten-4": "#E1BEE7",
    "purple-lighten-3": "#CE93D8",
    "purple-lighten-2": "#BA68C8",
    "purple-lighten-1": "#AB47BC",
    "purple-darken-1": "#8E24AA",
    "purple-darken-2": "#7B1FA2",
    "purple-darken-3": "#6A1B9A",
    "purple-darken-4": "#4A148C",
    "purple-accent-1": "#EA80FC",
    "purple-accent-2": "#E040FB",
    "purple-accent-3": "#D500F9",
    "purple-accent-4": "#AA00FF",
  },
};

export { DEFAULT_LIGHT_THEME };
